INCLUDE(SetDefaultAndFromEnv)

# Must match what is in CDash project 'LifeV'
SET(CTEST_NIGHTLY_START_TIME "02:00:00 UTC") # 10 PM MDT or 9 PM MST

# Set actual CTest/CDash settings

IF (NOT DEFINED CTEST_DROP_METHOD)
  SET_DEFAULT_AND_FROM_ENV(CTEST_DROP_METHOD "http")
ENDIF()

IF (CTEST_DROP_METHOD STREQUAL "http")
  SET_DEFAULT_AND_FROM_ENV(CTEST_DROP_SITE "cmcsforge.epfl.ch")
  SET_DEFAULT_AND_FROM_ENV(CTEST_PROJECT_NAME "LifeV")
  SET_DEFAULT_AND_FROM_ENV(CTEST_DROP_LOCATION "/cdash/submit.php?project=LifeV")
  SET_DEFAULT_AND_FROM_ENV(CTEST_TRIGGER_SITE "")
  SET_DEFAULT_AND_FROM_ENV(CTEST_DROP_SITE_CDASH TRUE)
ENDIF()
