#! /bin/bash
#
# author: Antonio Cervone <ant.cervone@gmail.com>
# date:   23-03-2012
#

# this script takes care of just the headers, no library is compiled

ver="1.48.0"

download_boost() {
  wget http://gitorious.org/boost/cmake/archive-tarball/cmake-${ver}
}

unpack_boost() {
  mv cmake-${ver} boost-cmake-${ver}.tar.gz
  tar xzf boost-cmake-${ver}.tar.gz
}

build_boost() {
  :
}

install_boost() {
  install -m 755 -d $install_dir
  install -m 755 -d $install_dir/include
  cp -r $src_dir/boost-cmake/boost $install_dir/include
}

