#! /bin/bash
#
# author: Antonio Cervone <ant.cervone@gmail.com>
# date:   23-03-2012
#

# this script takes care of just the headers, no library is compiled

ver="1.48.0"
_ver="1_48_0"

download_boost() {
  wget -c http://downloads.sourceforge.net/project/boost/boost/${ver}/boost_${_ver}.tar.gz
}

unpack_boost() {
  tar xzf boost_${_ver}.tar.gz
}

build_boost() {
  :
}

install_boost() {
  install -m 755 -d $install_dir
  install -m 755 -d $install_dir/include
  cp -r $src_dir/boost_${_ver}/boost $install_dir/include
}

