#! /bin/bash
#
# author: Antonio Cervone <ant.cervone@gmail.com>
# date:   22-03-2012
#

ver="3.1.1"

download_parmetis() {
  wget http://glaros.dtc.umn.edu/gkhome/fetch/sw/parmetis/OLD/ParMetis-$ver.tar.gz
}

unpack_parmetis() {
  tar xzf ParMetis-$ver.tar.gz
}

build_parmetis() {

  # no support for off-source building
  cd $src_dir/ParMetis-$ver || return 1

  cat > Makefile.in <<EOF
CC = ${mpi_bin}/mpicc
OPTFLAGS = $CFLAGS -fPIC
LD = ${mpi_bin}/mpicc
AR = ar rv
RANLIB = ar -ts
EOF
  make clean || return 1
  make || return 1
}

install_parmetis() {
  install -m 775 -d ${install_dir}/{lib,include}
  install -m 664 lib{metis,parmetis}.a ${install_dir}/lib
  install -m 775 -d ${install_dir}/include/metis
  install -m 664 METISLib/*.h ${install_dir}/include/metis
  install -m 664 parmetis.h ${install_dir}/include
}

