#! /bin/bash
#
# author: Antonio Cervone <ant.cervone@gmail.com>
# date:   22-03-2012
#

ver="1.48.0"

download_boostlib() {
    wget -c http://gitorious.org/boost/cmake/archive-tarball/cmake-$ver
}

unpack_boostlib() {
  mv cmake-$ver boost-cmake-${ver}.tar.gz
  tar xvf boost-cmake-${ver}.tar.gz
}

build_boostlib() {
  cmake \
    -DCMAKE_INSTALL_PREFIX=${install_dir} \
    -DINSTALL_VERSIONED:BOOL=OFF \
    ${src_dir}/boost-cmake

  make

}

install_boostlib() {
  make install
}
