#! /bin/bash
#
# author: Antonio Cervone <ant.cervone@gmail.com>
# date:   11-12-2012
#

ver="3.1"

download_clang() {
    wget -c http://llvm.org/releases/${ver}/llvm-${ver}.src.tar.gz || return 1
    wget -c http://llvm.org/releases/${ver}/clang-${ver}.src.tar.gz || return 1
    wget -c http://llvm.org/releases/${ver}/compiler-rt-${ver}.src.tar.gz || return 1
}

unpack_clang() {
    tar xzf llvm-${ver}.src.tar.gz || return 1
    tar xzf clang-${ver}.src.tar.gz || return 1
    mv clang-${ver}.src llvm-${ver}.src/tools/clang
    tar xzf compiler-rt-${ver}.src.tar.gz || return 1
    mv compiler-rt-${ver}.src llvm-${ver}.src/projects/compiler-rt
}

build_clang() {
    # due to a bug in the compiler-rt package we need to add a fake CmakeLists.txt
    touch ${src_dir}/llvm-${ver}.src/projects/compiler-rt/test/CMakeLists.txt

    rm -f CMakeCache.txt
    rm -fr CMakeFiles

    ${cmake_bin}/cmake \
        -D CMAKE_BUILD_TYPE:STRING="Release" \
        -D CMAKE_INSTALL_PREFIX:PATH=${install_dir} \
        \
        ${src_dir}/llvm-${ver}.src || return 1

#        -D LLVM_ENABLE_FFI:BOOL=ON \
#        \
#        -D FFI_INCLUDE_DIR:PATH="/usr/include/i386-linux-gnu" \
#        -D FFI_LIBRARY_DIR:PATH="/usr/lib/i386-linux-gnu" \
#        \

  make || return 1
}

install_clang() {
  make install || return 1
}

