#! /bin/bash
#
# author: Davide baroli <davide.baroli@gmail.com>
# contributor: Antonio Cervone <ant.cervone@gmail.com>
# date: 2013-03-11
#

ver='2010.1'

download_qhull() {
  wget -c "http://www.qhull.org/download/qhull-${ver}-src.tgz" || return 1
  cp ${package_root}/qhull.patch . || return 1
}

unpack_qhull() { 
  tar xzf qhull-${ver}-src.tgz || return 1
}

build_qhull() {

  pushd ${src_dir}/qhull-${ver}
    patch -p1 < ${src_dir}/qhull.patch || return 1
  popd
    
  rm -f CMakeCache.txt
  rm -rf CMakeFiles

  ${cmake_bin}/cmake \
    -DCMAKE_INSTALL_PREFIX=${install_dir} \
    $EXTRAOPTS  \
    -DCMAKE_CFLAGS="${CFLAGS} -fno-strict-aliasing -ansi" \
    -DCMAKE_CXXFLAGS="${CXXFLAGS} -fno-strict-aliasing -ansi" \
    \
    ${src_dir}/qhull-$ver || return 1
  
  make -j$NUM_PROC || return 1
}

install_qhull() {
  make -j$NUM_PROC install || return 1
}







