#! /bin/bash
#
# author: Antonio Cervone <ant.cervone@gmail.com>
# date:   22-03-2012
#

ver="1.48.0"

download_boostlib() {
    wget -c http://gitorious.org/boost/cmake/archive-tarball/cmake-$ver || return 1
}

unpack_boostlib() {
  mv cmake-$ver boost-cmake-${ver}.tar.gz
  tar xvf boost-cmake-${ver}.tar.gz || return 1
}

build_boostlib() {
  cmake \
    -DCMAKE_INSTALL_PREFIX=${install_dir} \
    -DINSTALL_VERSIONED:BOOL=OFF \
    ${src_dir}/boost-cmake || return 1

  make || return 1

}

install_boostlib() {
  make install || return 1
}
