#! /bin/bash
#
# author: Antonio Cervone <ant.cervone@gmail.com>
# date:   28-03-2012
#

# include configuration file
source libpath

pushd app > /dev/null # app

  SRC_DIR=${PWD}

  mkdir -p ${BUILD_DIR}/app

  pushd ${BUILD_DIR}/app > /dev/null # ${BUILD_DIR}/app

  rm -fr CMake*

  ${cmake_bin}/cmake \
    -D CMAKE_INSTALL_PREFIX:PATH=${INSTALL_DIR}/app_install \
    -D LifeV_DIR:PATH=${INSTALL_DIR}/lib/lifev \
    ${SRC_DIR} || exit

  make -j${NUM_PROC} || exit

  popd > /dev/null # ${BUILD_DIR}/app

popd > /dev/null # app

