#! /bin/bash
#
# author: Antonio Cervone <ant.cervone@gmail.com>
# date:   28-03-2012
#

# exit on every error
set -e

# include configuration file
source libpath

# set globally the number of processes to use
export MAKEFLAGS="-j$NUM_PROC"

pushd app > /dev/null # app

  SRC_DIR=${PWD}

  mkdir -p ${BUILD_DIR}/app

  pushd ${BUILD_DIR}/app > /dev/null # ${BUILD_DIR}/app

  rm -fr CMake*

  ${cmake_bin}/cmake \
    -D CMAKE_INSTALL_PREFIX:PATH=${INSTALL_DIR}/app_install \
    -D LifeV_DIR:PATH=${INSTALL_DIR}/lib/lifevlib \
    ${SRC_DIR} || exit

  make || exit

  popd > /dev/null # ${BUILD_DIR}/app

popd > /dev/null # app

