#! /bin/bash
#
# author: Antonio Cervone <ant.cervone@gmail.com>
# date:   28-03-2012
#

# comment next line to disable debug output
#DBG=1

# select library installation path
INSTALL_DIR=${HOME}/lifev/install

# select temporary build directory
BUILD_DIR=${HOME}/lifev/build

# comment next line to keep build files
RM_TMP=1

# comment next line to avoid log files
#LOG=1

# comment next line to disable download
DOWNLOAD=1

# comment next line to disable unpack
UNPACK=1

# check if we are using a mox machine
if [ $( uname -a | grep polimi ) ]; then MOX_MACHINE=1; fi

# set number of parallel builds to use
NUM_PROC=$(grep processor /proc/cpuinfo | wc -l)
if [ $NUM_PROC -gt 8 ]; then NUM_PROC=8; fi
echo "using $NUM_PROC parallel builds"

